### ISSUE TITLE
label shapes and input shapes for training 

### ISSUE THREAD

**Issue by WeheliyeHashi** [kirkegaardlab/deeptangle#13]
Hi,
Thanks again for your well written code!

I just a had one small question regarding the training of my dataset.

For example when I run the simulation dataset of your code, I get the following shapes for the input (X) and the labels (y), respectively:

X.shape = (1,5,10,256,256)
y.shape = (1, 5, 2, 3, 49, 2)

my hyper parameters are as follows:
batch_size =5
nframes =10

Basically, I want to be able to train for all the time step and not the first three time steps as shown for the y shape. When I set the "entire_clip" Boolean to True (in the dataset.py file), I get the label shape  as  (1, 5, 10, 2, 49, 2). This is the true label that I want to train. However, when I start the training I get the following error :
 
sub got incompatible shapes for broadcasting: (5, 1, 2048, 3, 49, 2), (5, 10, 1, 2, 49, 2)

Any suggestion on how to train on whole time steps labels rather than the first three. Thanks again for your help!

**Comment by alonfnt** [comment]
Hi @WeheliyeHashi,

It would look like the model is outputting 3 splines per clip. That is set in `model.py` with 
`self.temporal_window = 3` (sorry for hard coding it). 


Feel free to modify it / add an argument to model to make it work with larger temporal windows.
Since the final code trained on a set of 3 splines, I am unsure whether you will need to tweaks something else to make it work :)

**Comment by WeheliyeHashi** [comment]
Fixed it! Thanks!

I modified the code in the model.py slightly to fit the whole time steps. One thing that needs to be done is that the returned labled needs to be reshaped as follows:
 X, y, W = next(datasets[idx])
 W=W.transpose((0,1, 3, 2,4,5))

where W is the labels with the whole time steps and y is the original label with three time steps .

Thanks once again!

**Comment by juliusbierk** [comment]
@WeheliyeHashi just to be very clear:

In our approach, for every input clip, we predict the spline position at a given frame and the neighboring two. This is the hardcoded `temporal_window = 3`. If you have a video with labels of splines in every frame, the optimal approach is to split this video into many smaller clips (say 11 frames long) and then keep only the labels for the middle three.
So for instance, if you have a 100 frame long clip, you could make

CLIP 1:  Frames: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, with labels on 5, 6, 7.
CLIP 2: Frames 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, with labels on 6, 7, 8,
on so on... until
CLIP 89: Frames: 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, with labels on 94, 95, 96.

then you can use the code directly without changing the `temporal_window` variable.
If you do change that variable, you will need to train a much more complex model as the model now needs to output many more splines in one pass.

Hope this makes sense to you.

**Comment by WeheliyeHashi** [comment]
@juliusbierk thank you very much that makes sense.

Just to confirm when you say clip I presume you mean the batch number. For example if you have input. dataset equal to 
X.shape = (1,5,10,256,256)

X[1,0,:,:,:] refers to clip 1. Am I correct in saying this ?

Thank you agian for your help!
